### ISSUE TITLE
Build fails on macOS 

### ISSUE THREAD

**Issue by jwoertink** [I3oris/ic#1]
I know you're still testing stuff out, but hopefully this will help you along the way. IC will be huge if it all works out! 🚀 

```
❯ make
Undefined symbols for architecture x86_64:
  "llvm::AtomicCmpXchgInst::AtomicCmpXchgInst(llvm::Value*, llvm::Value*, llvm::Value*, llvm::AtomicOrdering, llvm::AtomicOrdering, unsigned char, llvm::Instruction*)", referenced from:
      llvm::IRBuilder<llvm::ConstantFolder, llvm::IRBuilderDefaultInserter>::CreateAtomicCmpXchg(llvm::Value*, llvm::Value*, llvm::Value*, llvm::AtomicOrdering, llvm::AtomicOrdering, unsigned char) in llvm_ext.o
  "llvm::buildModuleSummaryIndex(llvm::Module const&, std::__1::function<llvm::BlockFrequencyInfo* (llvm::Function const&)>, llvm::ProfileSummaryInfo*)", referenced from:
      _LLVMExtWriteBitcodeWithSummaryToFile in llvm_ext.o
     (maybe you meant: llvm::buildModuleSummaryIndex(llvm::Module const&, std::__1::function<llvm::BlockFrequencyInfo* (llvm::Function const&)>, llvm::ProfileSummaryInfo*, std::__1::function<llvm::StackSafetyInfo const* (llvm::Function const&)>))
  "llvm::DIBuilder::createCompileUnit(unsigned int, llvm::DIFile*, llvm::StringRef, bool, llvm::StringRef, unsigned int, llvm::StringRef, llvm::DICompileUnit::DebugEmissionKind, unsigned long long, bool, bool, llvm::DICompileUnit::DebugNameTableKind, bool)", referenced from:
      _LLVMExtDIBuilderCreateCompileUnit in llvm_ext.o
     (maybe you meant: llvm::DIBuilder::createCompileUnit(unsigned int, llvm::DIFile*, llvm::StringRef, bool, llvm::StringRef, unsigned int, llvm::StringRef, llvm::DICompileUnit::DebugEmissionKind, unsigned long long, bool, bool, llvm::DICompileUnit::DebugNameTableKind, bool, llvm::StringRef, llvm::StringRef))
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc "${@}" -o /Users/jeremywoertink/Development/crystal/ic/ic  -rdynamic -L/usr/local/lib /usr/local/Cellar/crystal/1.0.0/src/llvm/ext/llvm_ext.o `"/usr/local/opt/llvm/bin/llvm-config" --libs --system-libs --ldflags 2> /dev/null` -lstdc++ -lpcre -lgc -lpthread /usr/local/Cellar/crystal/1.0.0/src/ext/libcrystal.a -L/usr/local/Cellar/libevent/2.1.12/lib -levent -liconv -ldl`
make: *** [ic] Error 1
```

```
❯ crystal -v
Crystal 1.0.0 (2021-03-22)

LLVM: 9.0.1
Default target: x86_64-apple-macosx
```

**Comment by I3oris** [comment]
Hello, maybe try this?:

```
xcode-select --install # shouldn't be needed, homebrew installs it for you
brew install \
  bdw-gc \
  gmp \
  libevent \
  libxml2 \
  libyaml \
  llvm \
  pcre \
  openssl \
  pkg-config
brew link --force llvm # it'll fail and give you instructions for adding llvm your PATH, do it, restart terminal.
```
from this [link](https://github.com/crystal-lang/crystal/wiki/All-required-libraries)

I've in effect forgot to tell in the README that you must install crystal compilation dependencies, since IC use crystal sources.

**Comment by jwoertink** [comment]
Looks like that didn't work on Crystal 1.0; however, I'm able to build the crystal compiler from source. 

```
ic on  master via 🔮 v1.0.0 took 3m46s
❯ crystal build src/ic.cr
Undefined symbols for architecture x86_64:
....
```

```
❯ /Users/jeremywoertink/Development/crystal/lang/bin/crystal -v
Using compiled compiler at .build/crystal
Crystal 1.1.0-dev [a7544b5f0] (2021-04-24)

LLVM: 11.1.0
Default target: x86_64-apple-macosx
```

Once I did that, it built ic:

```
❯ /Users/jeremywoertink/Development/crystal/lang/bin/crystal build src/ic.cr
Using compiled compiler at /Users/jeremywoertink/Development/crystal/lang/.build/crystal


ic on  master via 🔮 v1.0.0 took 48s
❯ ./ic

can't find file 'primitives'

If you're trying to require a shard:
- Did you remember to run `shards install`?
- Did you make sure you're running the compiler in the same directory as your shard.yml?
ic(1.1.0-dev):01> 1 + 1
undefined method '+' for Int32
```

Progress!

**Comment by I3oris** [comment]
Oh, I know this error, this append because some environment variables must be set a the compilation for IC knows the location of std-lib (for now I use only the file primitive.cr and class.cr)

the env to set is:
`CRYSTAL_PATH` `CRYSTAL_LIBRARY_PATH`

The values are the same as those given by `crystal env`

so something like that should works, I hope :wink: 
```
export CRYSTAL_PATH=$(crystal env CRYSTAL_PATH)
export CRYSTAL_LIBRARY_PATH=$(crystal env CRYSTAL_PATH)
/Users/jeremywoertink/Development/crystal/lang/bin/crystal build src/ic.cr
```

It what happens when you use the makefile  

 However I don't know why only works with your local version of crystal ? :thinking:

**Comment by jwoertink** [comment]
ah ha! 

```
ic on  master via 🔮 v1.0.0 took 48s
❯ ./ic
ic(1.1.0-dev):01> 1 + 1
 => 2
ic(1.1.0-dev):02> __
 => 2
```

🎉  Awesome! Thanks for your help. Great work on this so far. I guess we can close this out now that the mystery is solved 😄

**Comment by I3oris** [comment]
Great ! :tada: 

> the mystery is solved

Not completely since it was not working with just `make` .. :slightly_frowning_face: 
I guess I am missing some environment variable into my makefile, compared to the to crystal one (https://github.com/crystal-lang/crystal/blob/master/Makefile) :smile: 

I must look that more in details. 

Thanks you for your interest and for notice that! :smiley: , since lot of crystal people use mac it would be preferable if it works on it!

**Comment by I3oris** [comment]
I think I have found the problem:

When llvm is used in a project, the crystal compiler will try to use the command
``cc ... /usr/local/Cellar/crystal/1.0.0/src/llvm/ext/llvm_ext.o `"/usr/local/opt/llvm/bin/llvm-config" --libs --system-libs --ldflags` ...``
which will use the llvm lib installed on the system (`llvm-config --libs`), with the `llvm_ext.o` of the crystal std lib (`/usr/local/..`).

But if this compiler was compiled with a different version of llvm (so the `.o` also), the `.o` become incompatible with the llvm lib on the system, and the symbols are not found.

That why its works with a compiler from source, which will use a `llvm_ext.o` up to date with llvm on the system.

For now, the best thing I can do is to tell that IC should be compiled with a  llvm version (`crystal -v`) similar to `llvm-config --version`

**Comment by jwoertink** [comment]
Sweet! Good work finding that. That should make it easier for others to hop on and start playing with it too.
